name: Android Release APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter 3.35.4 (Dart >= 3.8)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      - name: Show Flutter/Dart versions
        run: flutter --version

      - name: Android SDK packages (API 36 + build-tools)
        shell: bash
        run: |
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-36" \
            "build-tools;36.0.0" \
            "platforms;android-33" \
            "cmake;3.22.1" \
            "ndk;27.0.12077973" || true

      - name: Flutter pub get
        run: flutter pub get

      - name: Ensure asset directories exist
        run: |
          mkdir -p assets/audio assets/images
          [ -f assets/audio/.gitkeep ] || echo "# placeholder" > assets/audio/.gitkeep
          [ -f assets/images/.gitkeep ] || echo "# placeholder" > assets/images/.gitkeep

      - name: Build release APK
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL || 'https://example.com' }}
        run: |
          flutter clean
          flutter build apk --release --dart-define=API_BASE_URL=${API_BASE_URL}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
