# .github/workflows/build.yml (snippet)
- name: Set up Java 17
  uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: '17'

- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    flutter-version: '3.24.1'

- name: Flutter build (release)
  run: |
    flutter pub get
    flutter build apk --release --dart-define=API_BASE_URL=https://your.api
